-- Run this AFTER creating the skin_test_questions table

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (1, 'Yuzunuzu yikadiktan 2 saat sonra cildiniz nasil hissediyor?', 'How does your skin feel 2 hours after washing?', '[{"label_tr":"Gergin ve pul pul dokulmeye meyilli","label_en":"Tight and prone to flaking","scores":{"kuru":3,"normal":0,"karma":0,"yagli":0,"hassas":1}},{"label_tr":"Rahat, ne yagli ne kuru","label_en":"Comfortable, neither oily nor dry","scores":{"kuru":0,"normal":3,"karma":0,"yagli":0,"hassas":0}},{"label_tr":"Sadece T bolgesi parliyor","label_en":"Only the T-zone is shiny","scores":{"kuru":0,"normal":0,"karma":3,"yagli":1,"hassas":0}},{"label_tr":"Her yer parliyor ve yagli","label_en":"Everything is shiny and oily","scores":{"kuru":0,"normal":0,"karma":0,"yagli":3,"hassas":0}}]'::jsonb);

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (2, 'Gun ortasinda gozeneklerinizin durumu nedir?', 'What do your pores look like at midday?', '[{"label_tr":"Neredeyse hic gorunmuyorlar","label_en":"Almost invisible","scores":{"kuru":3,"normal":1,"karma":0,"yagli":0,"hassas":0}},{"label_tr":"Sadece burun cevresinde hafif belli","label_en":"Slightly visible around the nose","scores":{"kuru":0,"normal":3,"karma":1,"yagli":0,"hassas":0}},{"label_tr":"T bolgesinde oldukca belirgin","label_en":"Quite visible in the T-zone","scores":{"kuru":0,"normal":0,"karma":3,"yagli":1,"hassas":0}},{"label_tr":"Her yerde genis gozenekler var","label_en":"Large pores everywhere","scores":{"kuru":0,"normal":0,"karma":0,"yagli":3,"hassas":0}}]'::jsonb);

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (3, 'Ne siklikla sivilce veya siyah nokta sorunu yasiyorsunuz?', 'How often do you experience acne or blackheads?', '[{"label_tr":"Nadiren veya hic","label_en":"Rarely or never","scores":{"kuru":2,"normal":2,"karma":0,"yagli":0,"hassas":0}},{"label_tr":"Sadece regl veya stresli zamanlarda","label_en":"Only during period or stress","scores":{"kuru":0,"normal":2,"karma":1,"yagli":0,"hassas":1}},{"label_tr":"Ayda en az bir kez, T bolgesinde","label_en":"Monthly, usually T-zone","scores":{"kuru":0,"normal":0,"karma":3,"yagli":1,"hassas":0}},{"label_tr":"Surekli ve yaygin","label_en":"Constant and widespread","scores":{"kuru":0,"normal":0,"karma":0,"yagli":3,"hassas":1}}]'::jsonb);

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (4, 'Yeni bir urun denediginizde cildiniz nasil tepki verir?', 'How does your skin react to new products?', '[{"label_tr":"Sorunsuz kabul eder","label_en":"Accepts without problems","scores":{"kuru":0,"normal":3,"karma":1,"yagli":1,"hassas":0}},{"label_tr":"Hafif karincilanma olur ama gecer","label_en":"Slight tingling but passes","scores":{"kuru":1,"normal":1,"karma":1,"yagli":0,"hassas":1}},{"label_tr":"Siklikla kizarir veya yanar","label_en":"Often gets red or burns","scores":{"kuru":0,"normal":0,"karma":0,"yagli":0,"hassas":3}},{"label_tr":"Her yeni urun irite eder","label_en":"Every new product irritates","scores":{"kuru":1,"normal":0,"karma":0,"yagli":0,"hassas":4}}]'::jsonb);

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (5, 'Gunese ciktiginizda cildinizde ne olur?', 'What happens to your skin in the sun?', '[{"label_tr":"Hemen kizaririm, bronzlasmam","label_en":"Immediately red, never tan","scores":{"kuru":1,"normal":0,"karma":0,"yagli":0,"hassas":3}},{"label_tr":"Once kizaririm, sonra bronzlasirim","label_en":"First red, then slight tan","scores":{"kuru":0,"normal":2,"karma":1,"yagli":0,"hassas":1}},{"label_tr":"Kolayca bronzlasirim","label_en":"Tan easily, rarely burn","scores":{"kuru":0,"normal":1,"karma":1,"yagli":1,"hassas":0}},{"label_tr":"Hic yanmadan kararirim","label_en":"Darken quickly without burning","scores":{"kuru":0,"normal":0,"karma":0,"yagli":2,"hassas":0}}]'::jsonb);

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (6, 'Sivilce izi ne kadar sure kaliyor?', 'How long do acne marks last?', '[{"label_tr":"Hizli iyilesir, iz kalmaz","label_en":"Heals quickly, no marks","scores":{"kuru":1,"normal":3,"karma":0,"yagli":0,"hassas":0}},{"label_tr":"Birkac haftada gecer","label_en":"Fades in a few weeks","scores":{"kuru":0,"normal":1,"karma":2,"yagli":1,"hassas":0}},{"label_tr":"Lekeler aylarca kalir","label_en":"Marks last for months","scores":{"kuru":0,"normal":0,"karma":1,"yagli":1,"hassas":2}},{"label_tr":"Kalici leke yapar","label_en":"Leaves permanent marks","scores":{"kuru":0,"normal":0,"karma":0,"yagli":0,"hassas":3}}]'::jsonb);

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (7, 'Gun icinde parlama ne zaman basliyor?', 'When does shine start during the day?', '[{"label_tr":"Hic parlama olmaz, hep mat","label_en":"No shine, always matte","scores":{"kuru":3,"normal":0,"karma":0,"yagli":0,"hassas":0}},{"label_tr":"Aksama dogru hafif parlama","label_en":"Slight shine towards evening","scores":{"kuru":0,"normal":3,"karma":0,"yagli":0,"hassas":0}},{"label_tr":"Ogle saatlerinde T bolge yaglanir","label_en":"T-zone oily around noon","scores":{"kuru":0,"normal":0,"karma":3,"yagli":1,"hassas":0}},{"label_tr":"1-2 saat sonra yaglanir","label_en":"Oily 1-2 hours after routine","scores":{"kuru":0,"normal":0,"karma":0,"yagli":3,"hassas":0}}]'::jsonb);

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (8, 'Mevsim gecislerinde cildiniz nasil degisir?', 'How does your skin change with seasons?', '[{"label_tr":"Asiri kurur ve catlar","label_en":"Extremely dry and cracked","scores":{"kuru":3,"normal":0,"karma":0,"yagli":0,"hassas":2}},{"label_tr":"Biraz daha nemsiz hissederim","label_en":"Feels less hydrated","scores":{"kuru":1,"normal":3,"karma":0,"yagli":0,"hassas":0}},{"label_tr":"Yanaklar kurur, T bolge ayni","label_en":"Cheeks dry, T-zone same","scores":{"kuru":0,"normal":0,"karma":3,"yagli":0,"hassas":0}},{"label_tr":"Degisiklik yok, hep yagli","label_en":"No change, always oily","scores":{"kuru":0,"normal":0,"karma":0,"yagli":3,"hassas":0}}]'::jsonb);

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (9, 'Cildinizde kizariklik ne kadar yaygin?', 'How common is redness on your skin?', '[{"label_tr":"Hic yok","label_en":"None at all","scores":{"kuru":0,"normal":2,"karma":1,"yagli":1,"hassas":0}},{"label_tr":"Burun kenarlarinda hafif","label_en":"Slightly around the nose","scores":{"kuru":1,"normal":1,"karma":0,"yagli":0,"hassas":1}},{"label_tr":"Yanaklarda belirginlesiyor","label_en":"Visible on cheeks","scores":{"kuru":0,"normal":0,"karma":0,"yagli":0,"hassas":3}},{"label_tr":"Yuzum hep kirmizimsi","label_en":"Face always reddish","scores":{"kuru":0,"normal":0,"karma":0,"yagli":0,"hassas":4}}]'::jsonb);

INSERT INTO skin_test_questions (question_order, text_tr, text_en, options) VALUES (10, 'Cildinize dokundugunuzda dokusu nasil?', 'How does your skin feel when touched?', '[{"label_tr":"Puruzlu ve nemsiz","label_en":"Rough and dehydrated","scores":{"kuru":3,"normal":0,"karma":0,"yagli":0,"hassas":1}},{"label_tr":"Yumusak ve puruzsuz","label_en":"Soft and smooth","scores":{"kuru":0,"normal":3,"karma":0,"yagli":0,"hassas":0}},{"label_tr":"Alin yagli, yanaklar yumusak","label_en":"Forehead oily, cheeks soft","scores":{"kuru":0,"normal":0,"karma":3,"yagli":0,"hassas":0}},{"label_tr":"Kaygan ve kalin tabaka gibi","label_en":"Slippery, thick layer feeling","scores":{"kuru":0,"normal":0,"karma":0,"yagli":3,"hassas":0}}]'::jsonb);
